#!/bin/bash

read -p "Enregistrer une note de commit verifie (y/[n]) ?" yn < /dev/tty
case $yn in
    [Yy]* )
        mkdir -p suivi
        echo "commit verifie le $(date)" > suivi/commitInfo.txt
        git add suivi/commitInfo.txt
        exit 0;;
    [Nn]* )
        exit 0;;
    * )
        exit 0;;
esac
exit 0

